### ISSUE TITLE
NO. of time a organisation appeared in 5 years

### ISSUE THREAD

**Issue by mangalutsav** [rohithasrk/GSoC-Organisation-Scraper#2]
The scraper should also be able to tell how many time organisation appeared in 5 years

**Comment by rohithasrk** [comment]
Yes. Definitely. But the website of archives has a different structure and therefore didn't do it. Would require a little more effort. Will implement it. :D

**Comment by rohithasrk** [comment]
Made a function. Which is returning the number of times it participated from the beginning to 2015. Not showing in the results because of high execution time which is highly undesirable.

**Comment by rohithasrk** [comment]
Maybe a json file would help for sure.

**Comment by rohithasrk** [comment]
Done.
