### ISSUE TITLE
Support for 2018 orgs

### ISSUE THREAD

**Issue by rohithasrk** [rohithasrk/GSoC-Organisation-Scraper#31]

**Comment by shubham76** [comment]
@rohithasrk So here we only want to list those organizations which are there for 2018, right?
Let's say some org A is not for 2018 but was there for 2017 and it supports Python.
Now if user query is 'Python' then we won't list out that organisation, right?
 
Also, I am not able to scrap the current organisations' list. [GSoc'18 Organisations](https://summerofcode.withgoogle.com/organizations/) Any idea why?
I fell you can't scrap it as it is being generated via back-end. The HTML page won't be there as it is there in archive pages of GSoC. What do you think?

**Comment by rohithasrk** [comment]
@shubham76 Right. You can't scrap them with the current single page algorithm as it the generated dynamically from the backend. But you can still scrap it using the API.

Yes. I want the scraper to scrape the 2018 orgs so that people use it for the present year. This would maybe require you to generate a new algorithm which scrapes the API. We want the orgs of 2018 and also the number of times they've appeared in the past. (I guess that's how it works right now.)

**Comment by shubham76** [comment]
@rohithasrk Oh. Are there any APIs available which will provide information about GSoC site? What are those? I would like to work on them to solve this issue.

**Comment by rohithasrk** [comment]
@shubham76. Definitely, there are APIs. Check out the network tab in the chrome/firefox developer tools and you can see the API request being made.

**Comment by RaiVaibhav** [comment]
@rohithasrk I created a basic scrapper based on Django after taking help from your comments.
@shubham76 Have a look at the [gsocdata.py script](https://github.com/RaiVaibhav/GSoC-2018-Scrap/blob/master/scrap/gsocdata.py)  for the issue.

**Comment by rohithasrk** [comment]
Hi @RaiVaibhav. Good work. Would be great if someone could add support to 2018 orgs here too.
