### ISSUE TITLE
UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

### ISSUE THREAD

**Issue by rohithasrk** [rohithasrk/GSoC-Organisation-Scraper#4]
Need to fix this.

**Comment by ulgens** [comment]
Where do you get this error? If you can give more details, i could look for it.

**Comment by rohithasrk** [comment]
![error](https://cloud.githubusercontent.com/assets/13820931/20876083/767c0b42-bae5-11e6-9b2e-a57169646110.png)

**Comment by ulgens** [comment]
Source of the problem is this line: https://github.com/rohithasrk/gsoc-organisation-scraper/blob/master/resources/2011.txt#L109

`str(org_name) in o2011` solves the problem.

**Comment by ulgens** [comment]
Hey, why did you open it back? Does the problem still exist?

**Comment by rohithasrk** [comment]
Not exactly. But doing org_name = str(org_name) results in some errors. Like this,

![this](https://cloud.githubusercontent.com/assets/13820931/21079269/34cbb6d4-bfb3-11e6-9ddd-83ebdeeb9ee5.png)

**Comment by rohithasrk** [comment]
Something better needs to be done.

**Comment by ulgens** [comment]
Oh okay, what was the search term?

**Comment by rohithasrk** [comment]
Oh! These were the results for 'python'.

**Comment by ulgens** [comment]
I didn't get same error last night, let me check it again, sorry. Which Python version do you working on?

**Comment by rohithasrk** [comment]
Python 2.7.6

**Comment by vinamarora8** [comment]
Fixed. Just disable the warnings, and don't use the 'str(org_name)' thing.
I don't think the warnings are important. They probably are about the program trying to convert weird characters into Unicode.
