### ISSUE TITLE
Python 3+ incompatible

### ISSUE THREAD

**Issue by dhruvkb** [rohithasrk/GSoC-Organisation-Scraper#8]
BeautifulSoup 3 does not work on Python 3+, recommend moving to BS4
raw_input("…") is now input("…")
print "…" is now print("…")

**Comment by nileshgulia1** [comment]
@rohithasrk  Does this issue solved?

**Comment by rohithasrk** [comment]
Not yet @nileshgulia1. Would you like to work on it?

**Comment by nileshgulia1** [comment]
@rohithasrk  Thanks for asking ,but I have lot others projects to work on,just asking bcoz I want to use the scraper and is not building bcoz of versioning problem. :)

**Comment by rohithasrk** [comment]
@nileshgulia1. That's okay. I'm picked up this week too. Till then you may try using it in a virtual environment.
